Add update board functionality #31
pytrello2/pytrello2 pull request #32
Opened 2023-12-17 18:49 UTC by jessat

This commit adds the update board functionality.
The tests are also updated accordingly.

Signed-off-by: jessat 14183940+jessat@users.noreply.github.com

2023-12-17 18:58 UTC, jessat commented
@vchrombie what do you think I should do here?  I unsuccessfully tried:
git commit --amend --author="jessat <[14183940+jessat@users.noreply.github.com>"
git push origin add-update-board -f

2023-12-19 18:13 UTC, vchrombie commented
Hi @jessat, thanks for the PR.

The problem is with the sign off. It has to be in the format of
```
Signed-off-by: Name <Email>
```

The email has to be enclosed within the `<` `>`. Your sign off of the two commits looks like this.
```
Signed-off-by: jessat 14183940+jessat@users.noreply.github.com
```

You can fix it by
```
git checkout add-update-board
git reset --soft HEAD~2
git commit -s -m "feat: Add update board functionality"
git fetch origin
git rebase master
git push origin add-update-board -f
```

Let me know if you need any help.

2023-12-20 05:19 UTC, vchrombie requested changes
Just a few more changes before we get in the PR.

You can also rebase to fetch the latest changes.

2023-12-20 05:19 UTC, vchrombie commented on tests/test_board.py
> +    board = board_manager.update_board("test_board_id", "name", "desc")
```suggestion
    board = board_manager.update_board("test_board_id")
```

2023-12-20 05:19 UTC, vchrombie commented on tests/test_board.py
> +    assert board.id == board_data["id"]
```suggestion
    assert board.id == board_data["id"]
    mock_http_client.put.assert_called_once_with("boards/test_board_id/", {})
```

2023-12-20 05:19 UTC, vchrombie commented on pytrello2/board.py
> +        return Board(board_data)
We started using `**kwargs` for the non-required parameters.
You can check the recent [implementation in `card.py`](https://github.com/pytrello2/pytrello2/blob/34ad7738e4321953f5df494afaa92d22fc485f98/pytrello2/card.py#L39).

2023-12-20 05:19 UTC, vchrombie commented on pytrello2/board.py
> +        """
You can maybe add the parameters in the doc string to follow the coding style.

2023-12-21 01:47 UTC, jessat commented
I created a new PR so it is cleaner.

2023-12-21 01:47 UTC, closed without merging